//
//  ChatGPTQuestions.swift
//  ChatAI2
//
//  Created by Thomas Woodfinon 24/2/23.
//
// swiftlint:disable line_length type_body_length file_length
import Foundation
class ChatGPTQuestion {
    static let questions = [ "How can I optimize my landing page for search engines?",
                            "What are the best practices for structuring the content on my landing page?",
                            "How can I make sure my landing page is mobile-friendly for SEO?",
                            "What are the key on-page SEO elements I should include on my landing page?",
                            "How can I use keywords effectively on my landing page to improve SEO?",
                            "How can I improve the loading speed of my landing page for SEO?",
                            "How can I make sure my landing page is accessible to users with disabilities for SEO?",
                            "How can I use social media to improve the SEO of my landing page?",
                            "How can I use internal linking to improve the SEO of my landing page?",
                            "How can I use external linking to improve the SEO of my landing page?",
                            "How can I use header tags to improve the SEO of my landing page?",
                            "How can I use alt tags for images to improve the SEO of my landing page?",
                            "How can I use schema markup to improve the SEO of my landing page?",
                            "How can I use analytics to track the performance of my landing page for SEO?",
                            "How can I use A/B testing to optimize my landing page for SEO?",
                            "How can I use voice search optimization for my landing page?",
                            "How can I use video content to improve the SEO of my landing page?",
                            "How can I use influencer marketing to improve the SEO of my landing page?",
                            "How can I use local SEO to optimize my landing page for nearby customers?",
                            "How can I use structured data to improve the SEO of my landing page?",
                            "How can I use long-tail keywords to improve the SEO of my landing page?",
                            "How can I use meta descriptions to improve the SEO of my landing page?",
                            "How can I use social signals to improve the SEO of my landing page?",
                            "How can I use backlinks to improve the SEO of my landing page?",
                            "How can I use Google My Business to improve the SEO of my landing page?",
                            "How can I use Google Search Console to improve the SEO of my landing page?",
                            "How can I use Google Analytics to improve the SEO of my landing page?",
                            "How can I use Google Tag Manager to improve the SEO of my landing page?",
                            "How can I use Google AdWords to improve the SEO of my landing page?",
                            "How can I use Google Trends to improve the SEO of my landing page?",
                            "How can I use Google Lighthouse to improve the SEO of my landing page?",
                            "How can I use Google PageSpeed Insights to improve the SEO of my landing page?",
                            "How can I use Google Search Ads to improve the SEO of my landing page?",
                            "How can I use Google Search Console to improve the SEO of my landing page?",
                            "How can I use Google Analytics Event Tracking to improve the SEO of my landing page?",
                            "How can I use Google Analytics Goal Tracking to improve the SEO of my landing page?",
                            "How can I use Google Analytics Custom Dimensions to improve the SEO of my landing page?",
                            "How can I use Google Analytics Custom Metrics to improve the SEO of my landing page?",
                            "How can I use Google Analytics Funnel Visualization to improve the SEO of my landing page?",
                            "How can I use Google Analytics Segments to improve the SEO of my landing page?",
                            "How can I use Google Analytics Channels to improve the SEO of my landing page?",
                            "How can I optimize my landing page for Bing search engine?",
                            "How can I optimize my landing page for Yahoo search engine?",
                            "How can I optimize my landing page for Baidu search engine?",
                            "How can I optimize my landing page for Yonder search engine?",
                            "How can I optimize my landing page for DuckDuckGo search engine?",
                            "How can I optimize my landing page for AOL search engine?",
                            "How can I optimize my landing page for Ask Jeeves search engine?",
                            "How can I optimize my landing page for Wolfram Alpha search engine?",
                            "How can I optimize my landing page for Alexa search engine?",
                            "How can I optimize my landing page for Sogou search engine?",
                            "How can I optimize my landing page for Never search engine?",
                            "How can I optimize my landing page for 360 Search engine?",
                            "How can I optimize my landing page for StartPage search engine?",
                            "How can I optimize my landing page for want search engine?",
                            "How can I optimize my landing page for Gigabits search engine?",
                            "How can I optimize my landing page for Exiled search engine?",
                            "How can I optimize my meta tags to improve my search engine rankings?",
                            "What is the importance of using meta tags in SEO?",
                            "How do I choose the right keywords to include in my meta tags?",
                            "Can too many meta tags harm my search engine rankings?",
                            "How do meta tags affect the click-through rate of my website?",
                            "How do I write effective meta descriptions to increase my search engine visibility?",
                            "Can you explain the difference between meta tags and header tags?",
                            "How do I optimize my meta tags for voice search?",
                            "How do I use meta tags to improve my local SEO?",
                            "How do I optimize meta tags for images and videos?",
                            "Can you give an example of an effective meta tag for e-commerce website?",
                            "How do I optimize meta tags for a blog?",
                            "How often should I update my meta tags?",
                            "How do I optimize meta tags for a multilingual website?",
                            "How do I track the performance of my meta tags?",
                            "How do I optimize meta tags for AMP pages?",
                            "How do I use meta tags to improve my mobile SEO?",
                            "How do I optimize meta tags for featured snippets?",
                            "How do I use meta tags to improve my website's accessibility?",
                            "Can you give me some best practices for meta tag optimization?",
                            "How do backlinks affect my search engine rankings?",
                            "What is the importance of backlinks in SEO?",
                            "How do I acquire high-quality backlinks for my website?",
                            "Can you explain the difference between do follow and nofollow links?",
                            "How do I track the number of backlinks to my website?",
                            "How do I find and monitor my backlinks?",
                            "How do I remove bad backlinks from my website?",
                            "How do I build backlinks for a new website?",
                            "How do I acquire backlinks from authoritative websites?",
                            "How do I use backlinks to improve my local SEO?",
                            "How do I acquire backlinks for a blog?",
                            "How do I acquire backlinks for an e-commerce website?",
                            "How do I acquire backlinks for a multilingual website?",
                            "How do I acquire backlinks for an AMP page?",
                            "How do I use backlinks to improve my mobile SEO?",
                            "How do I acquire backlinks from social media?",
                            "How do I use backlinks to improve my website's accessibility?",
                            "How do I acquire backlinks from forums and discussion boards?",
                            "How do I use backlinks to improve my website's trustworthiness?",
                            "How do I use backlinks to improve my website's domain authority?",
                            "How do I acquire backlinks from government and educational websites?",
                            "How do I use backlinks to improve my website's brand visibility?",
                            "How do I acquire backlinks from guest posts?",
                            "How do I use backlinks to improve my website's page authority?",
                            "How do I acquire backlinks from broken link building?",
                            "How do I use backlinks to improve my website's click-through rate?",
                            "How do I acquire backlinks from content syndication?",
                            "How do I use backlinks to improve my website's bounce rate?",
                            "How do I acquire backlinks from press releases?",
                            "How do I use backlinks to improve my website's conversion rate?",
                            "How can I improve my overall SEO strategy?",
                            "What are the most important factors in a successful SEO strategy?",
                            "How do I conduct a thorough SEO audit?",
                            "How do I create a content strategy to improve my SEO?",
                            "How do I use social media to improve my SEO?",
                            "How do I optimize my website for local SEO?",
                            "How do I improve my website's load speed to improve SEO?",
                            "How do I create an SEO-friendly website structure?",
                            "How do I use long-tail keywords to improve my SEO?",
                            "How do I use internal linking to improve my SEO?",
                            "How do I use analytics to track my SEO progress?",
                            "How do I use schema markup to improve my SEO?",
                            "How do I improve my website's mobile SEO?",
                            "How do I use voice search optimization to improve my SEO?",
                            "How do I use backlinks to improve my SEO?",
                            "How do I use meta tags to improve my SEO?",
                            "How do I use alt tags to improve my SEO?",
                            "How do I use header tags to improve my SEO?",
                            "How do I use structured data to improve my SEO?",
                            "How do I use multimedia to improve my SEO?",
                            "How do I use Google My Business to improve my local SEO?",
                            "How do I use Google Search Console to improve my SEO?",
                            "How do I use Google Analytics to improve my SEO?",
                            "How do I improve my website's user experience to improve SEO?",
                            "How do I use AMP to improve my website's mobile SEO?",
                            "How do I use Google Tag Manager to improve my SEO?",
                            "How do I use Google Lighthouse to improve my website's performance and SEO?",
                            "How do I use A/B testing to improve my website's conversion rate and SEO?",
                            "How do I use heat map analysis to improve my website's user experience and SEO?",
                            "How do I use website personalization to improve my website's conversion rate and SEO?",
                            "How do I conduct keyword research for my website?",
                            "What tools can I use for keyword research?",
                            "How do I find long-tail keywords?",
                            "How do I find and use relevant keywords?",
                            "How do I track my keyword rankings?",
                            "How do I find and use LSI keywords?",
                            "How do I use keyword research to improve my content?",
                            "How do I use keyword research to improve my website's structure?",
                            "How do I use keyword research to improve my meta tags?",
                            "How do I use keyword research to improve my backlinks?",
                            "How do I use keyword research to improve my local SEO?",
                            "How do I use keyword research to improve my mobile SEO?",
                            "How do I use keyword research to improve my voice search optimization?",
                            "How do I use keyword research to improve my social media presence?",
                            "How do I use keyword research to identify my competitors?",
                            "How do I use keyword research to improve my PPC campaigns?",
                            "How do I use keyword research to improve my website's click-through rate?",
                            "How do I use keyword research to improve my website's conversion rate?",
                            "How do I use keyword research to improve my website's bounce rate?",
                            "How do I use keyword research to improve my website's accessibility?",
                            "How do I use keyword research to improve my website's trustworthiness?",
                            "How do I use keyword research to improve my website's domain authority?",
                            "How do I use keyword research to improve my website's brand visibility?",
                            "How do I use keyword research to improve my website's page authority?",
                            "How do I use keyword research to find new business opportunities?",
                            "How do I use keyword research to find and target niche markets?",
                            "How do I fix crawl errors on my website?",
                            "How do I fix broken links on my website?",
                            "How do I optimize my website's load speed?",
                            "How do I fix duplicate content issues on my website?",
                            "How do I fix incorrect redirects on my website?",
                            "How do I fix issues with my website's structured data?",
                            "How do I fix issues with my website's mobile optimization?",
                            "How do I fix issues with my website's AMP implementation?",
                            "How do I fix issues with my website's flag implementation?",
                            "How do I fix issues with my website's robots.txt file?",
                            "How do I fix issues with my website's XML sitemap?",
                            "How do I fix issues with my website's canonicalization?",
                            "How do I fix issues with my website's internal linking?",
                            "How do I fix issues with my website's navigation?",
                            "How do I fix issues with my website's breadcrumb implementation?",
                            "How do I fix issues with my website's pagination?",
                            "How do I fix issues with my website's schema markup?",
                            "How do I fix issues with my website's alt tags?",
                            "How do I fix issues with my website's header tags?",
                            "How do I fix issues with my website's micro data?",
                            "How do I fix issues with my website's structured data?",
                            "How do I fix issues with my website's JSON-LD?",
                            "How do I fix issues with my website's Open Graph tags?",
                            "How do I fix issues with my website's Twitter Cards?",
                            "How do I fix issues with my website's rich snippets?",
                            "How do I fix issues with my website's breadcrumb schema?",
                            "How do I fix issues with my website's FAQ schema?",
                            "How do I fix issues with my website's how-to schema?",
                            "How do I fix issues with my website's Q&A schema?",
                            "How do I fix issues with my website's video schema?",
                            "How do I fix issues with my website's news article schema?",
                            "How do I fix issues with my website's product schema?",
                            "How do I fix issues with my website's recipe schema?",
                            "How do I fix issues with my website's event schema?",
                            "How do I fix issues with my website's service schema?",
                            "How do I fix issues with my website's review schema?",
                            "How do I fix issues with my website's software application schema?",
                            "How do I fix issues with my website's local business schema?",
                            "How do I fix issues with my website's organization schema?",
                            "How do I fix issues with my website's person schema?",
                            "How do I track my website's traffic using analytics?",
                            "What analytics tools should I use to track my website's performance?",
                            "How do I track my website's bounce rate using analytics?",
                            "How do I track my website's conversion rate using analytics?",
                            "How do I track my website's click-through rate using analytics?",
                            "How do I track my website's pages per session using analytics?",
                            "How do I track my website's session duration using analytics?",
                            "How do I track my website's organic traffic using analytics?",
                            "How do I track my website's referral traffic using analytics?",
                            "How do I track my website's direct traffic using analytics?",
                            "How do I track my website's social media traffic using analytics?",
                            "How do I track my website's paid traffic using analytics?",
                            "How do I track my website's email traffic using analytics?",
                            "How do I track my website's user behavior using analytics?",
                            "How do I track my website's audience demographics using analytics?",
                            "How do I track my website's audience interests using analytics?",
                            "How do I track my website's audience location using analytics?",
                            "How do I track my website's audience behavior using analytics?",
                            "How do I track my website's audience technology using analytics?",
                            "How do I track my website's audience mobile usage using analytics?",
                            "How do I track my website's audience engagement using analytics?",
                            "How do I track my website's audience loyalty using analytics?",
                            "How do I track my website's audience acquisition using analytics?",
                            "How do I track my website's audience retention using analytics?",
                            "How do I track my website's audience revenue using analytics?",
                            "How do I track my website's audience lifetime value using analytics?",
                            "How do I track my website's audience funnels using analytics?",
                            "How do I track my website's audience paths using analytics?",
                            "How do I track my website's audience flow using analytics?",
                            "How do I track my website's audience segments using analytics?",
                            "How do I track my website's audience micro segments using analytics?",
                            "How do I track my website's audience cohorts using analytics?",
                            "How do I track my website's audience acquisition cost using analytics?",
                            "How do I track my website's audience lifetime revenue using analytics?",
                            "How do I track my website's audience net promoter score using analytics?",
                            "How do I track my website's audience customer satisfaction using analytics?",
                            "How do I track my website's audience customer loyalty using analytics?",
                            "How do I track my website's audience customer retention using analytics?",
                            "How do I track my website's audience customer lifetime value using analytics?",
                            "How do I track my website's audience customer journey using analytics?",
                            "How do I conduct a comprehensive SEO audit?",
                            "How do I identify and fix technical SEO issues?",
                            "How do I create a keyword research strategy?",
                            "How do I optimize my website's content for search engines?",
                            "How do I build high-quality backlinks for my website?",
                            "How do I optimize my website's meta tags for better search engine visibility?",
                            "How do I improve my website's load speed for better search engine rankings?",
                            "How do I use schema markup to enhance my website's search engine visibility?",
                            "How do I optimize my website for local SEO?",
                            "How do I improve my website's mobile SEO?",
                            "How do I optimize my website for voice search?",
                            "How do I use social media to improve my website's search engine visibility?",
                            "How do I improve my website's user experience to boost search engine rankings?",
                            "How do I optimize my website's images and videos for better search engine visibility?",
                            "How do I use analytics to track and improve my website's search engine performance?",
                            "How do I use A/B testing to improve my website's search engine visibility?",
                            "How do I use heat map analysis to improve my website's user experience and search engine visibility?",
                            "How do I use website personalization to improve my website's search engine visibility?",
                            "How do I optimize my website for featured snippets?",
                            "How do I use structured data to improve my website's search engine visibility?",
                            "How do I use internal linking to improve my website's search engine visibility?",
                            "How do I use alt tags and header tags to improve my website's search engine visibility?",
                            "How do I improve my website's accessibility for better search engine visibility?",
                            "How do I improve my website's trustworthiness for better search engine visibility?",
                            "How do I use AMP to improve my website's mobile search engine visibility?",
                            "How do I use Google Tag Manager to improve my website's search engine visibility?",
                            "How do I use Google Lighthouse to improve my website's performance and search engine visibility?",
                            "How do I use Google My Business to improve my local search engine visibility?",
                            "How do I use Google Search Console to improve my website's search engine visibility?",
                            "How do I use Google Analytics to improve my website's search engine visibility?",
                            "How do I research my competitors' SEO strategies?",
                            "How can I identify my competitors' top keywords?",
                            "How do I outrank my competitors in search engine results?",
                            "How can I find opportunities to improve my search engine visibility based on my competitors?",
                            "How do I stay up-to-date on my competitors' search engine rankings?",
                            "How do I track my competitors' backlink profiles?",
                            "How do I use my competitors' data to improve my own SEO strategy?",
                            "How can I use my competitors' strengths and weaknesses to my advantage in search engine rankings?",
                            "How do I use my competitors' PPC strategies to improve my own SEO?",
                            "How do I use my competitors' social media presence to improve my own SEO?",
                            "How do I use my competitors' website design to improve my own SEO?",
                            "How do I use my competitors' content strategy to improve my own SEO?",
                            "How do I use my competitors' internal linking to improve my own SEO?",
                            "How do I use my competitors' meta tags to improve my own SEO?",
                            "How do I use my competitors' schema markup to improve my own SEO?",
                            "How do I use my competitors' AMP implementation to improve my own SEO?",
                            "How do I use my competitors' flag implementation to improve my own SEO?",
                            "How do I use my competitors' mobile optimization to improve my own SEO?",
                            "How do I use my competitors' voice search optimization to improve my own SEO?",
                            "How do I use my competitors' local SEO to improve my own SEO?",
                            "How do I use my competitors' analytics to improve my own SEO?",
                            "How do I use my competitors' A/B testing to improve my own SEO?",
                            "How do I use my competitors' heat map analysis to improve my own SEO?",
                            "How do I use my competitors' website personalization to improve my own SEO?",
                            "How do I use my competitors' featured snippets to improve my own SEO?",
                            "How do I use my competitors' structured data to improve my own SEO?",
                            "How do I use my competitors' search engine visibility to improve my own SEO?"
    ]

    static let modifiableQuestions = [

        "I’m looking for a [type of text] that will speak directly to the needs and pain points of my [ideal customer persona] and persuade them to take [desired action] with a sense of urgency and strong offer.",

        "Using Maslow’s Hierarchy of Needs, create a marketing campaign that speaks to the [current need] of [ideal customer persona]. Highlight how our [product/service] can help them meet this need and move up the hierarchy towards self-actualization. Use language that resonates with their current stage in the hierarchy and addresses their specific needs and goals.",

        "Using the ‘Compare-Contrast’ framework, please write a marketing campaign outline that compares and contrasts two or more options or ideas to help [ideal customer persona] make an informed decision. Explain the pros and cons of each option and provide examples to support your points.",

        "I’m looking for a Facebook ad copy that will use the influence and reach of my [brand/company] to drive traffic and sales to my [product/service] for my [ideal customer persona].",

        "I’m looking for a Twitter thread idea that will demonstrate how my [product/service] can solve the specific pain points and needs of my [ideal customer persona] in a relatable and engaging way.",

        "I need an Instagram story idea that will showcase the unique and personal experiences of my [ideal customer persona] with my [product/service] and persuade them to share their positive review with their followers.",

        "I’m looking for a YouTube video idea that will provide a step-by-step guide on how to use my [product/service] and persuade my [ideal customer persona] to make a purchase with clear and compelling instructions.",

        "Act as a Personal Chef: I want you to act as my personal chef. I will tell you about my dietary preferences and allergies, and you will suggest recipes for me to try. You should only reply with the recipes you recommend, and nothing else. Do not write explanations. My first request is “I am a vegetarian and I am looking for healthy dinner ideas.",

        "I’m looking for an influencer marketing campaign outline that will leverage the social proof and credibility of [influencer type] to persuade my [ideal customer persona] to try our [product/service] and share their positive experience with their followers.",

        "I need a cold email idea that will provide a unique and compelling offer to my [ideal customer persona] and persuade them to take [desired action] with a sense of urgency and exclusivity."
    ]

    static let Prompts = [
        "How long does my CBD last when sitting on my dresser?",
        "Will CBD help with my arthritis?",
        "Will CBD help with my Anxiety?",
        "Will CBD help improve my Memory?",
        "Will CBD help improve my Mood?",
        "Will CBD  help my Cravings for Sugar?",
        "Will CBD help my Cravings for Alcohol?",
        "Will CBD help my Head Aches?",
        "Will CBD help my with my Stress?",
        "Will CBD help with my Eating Disorder?",
        "Will CBD help with my Cancer Treat Side Effects?",
        "Will CBD help with my Diabetes?",
        "Will CBD help with my Nausea?",
        "Will CBD help with my Fibromyalgia?",
        "Will CBD help with my Glaucoma?",
        "Will CBD help with my Depression?",
        "Will CBD help with my Sleep disorder?",
        "Will CBD help with my Inflammation?",
        "Will CBD help with my Dementia?",
        "Will CBD help with my Migraine?",
        "Will CBD help with my Epilepsy?",
        "Will CBD help with my Autoimmune Disease?",
        "Will CBD help with my Insomnia?",
        "Will CBD help with my Addition to Opioids?",
        "Will CBD help with my High Blood Pressure?",
        "Will CBD help with my Erectile Disfunction?",
        "Will CBD help with my Mental Clarity?",
        "Will CBD help with my Loss of Taste Due to Covid?",
        "Will CBD help with my Hair Loss?",
        "Will CBD help with my Metopes?",
        "Will CBD help with my Melanoma?",
        "Will CBD help with my Tinnitus?",
        "Will CBD help with my Appetite?",
        "Will CBD help with my IBS?",
        "Will CBD help with my Irritable Bowl Syndrome?",
        "Will CBD help with my Anger?",
        "Will CBD help with my Autism?",
        "Will CBD help with my Autistic Child?",
        "Will CBD help with my Asthma?",
        "Will CBD help with my Acne?",
        "Will CBD help with my Energy Levels?",
        "Will CBD help with my Eczema?",
        "Will CBD help with my Psoriasis?",
        "Will CBD help with my Sore Mussels?",
        "Will CBD help with my Work Out Recovery?",
        "Will CBD help with my Knee Pain?",
        "Will CBD help with my Joint Pain?",
        "Will CBD help with my Tennis Elbow?",
        "Will CBD help with my Stiff Joints?",
        "Will CBD help with my Back Pain?",
        "Will CBD help with my Bladder Infection?",
        "Will CBD help with my Colon Cancer?",
        "Will CBD help with my Heart Disease?",
        "Will CBD help with my Lung Cancer?",
        "Will CBD help with my Tendentious?",
        "Will CBD help with my Winkles?",
        "Will CBD help with my Cold Sores?",
        "Will CBD help with my Cramps?",
        "Will CBD help with my Mental Alertness?",
        "Will CBD help with my Short Term Memory?",
        "Will CBD help with my Crepey Skin?",
        "Will CBD help with my Black Heads?",
        "Will CBD help with my Pimples?",
        "Will CBD help with my Boils?",
        "Will CBD help with my Sun Burn?",
        "Will CBD help with my Dark Circles under my Eyes?",
        "Will CBD help with my Vision?",
        "Will CBD help with my Sinusitis?",
        "Will CBD help with my Carpel Tunnel?",
        "Will CBD help with my Chapped Lips",
        "Will CBD help with my Jock Itch?",
        "Will CBD help with my Athletes Foot?",
        "Will CBD help with my Cellulite?",
        "Will CBD help with my Spider Veins?",
        "Will CBD help with my Toe Fungus?",
        "Will CBD help with my Dry Skin?",
        "Will CBD help with my Dark Circles?",
        "Will CBD help with my Fat Loss?",
        "Will CBD help with my Flatulence?",
        "Will CBD help with my Grow Hair?",
        "Will CBD help with my Hemorrhoids?",
        "Will CBD help with my Insect bites?",
        "Will CBD help with my Poison Ivy?",
        "Will CBD help with my Endometriosis?",
        "Will CBD help with my Over Active Bladder?",
        "Will CBD help with my Osteoporosis?",
        "Will CBD help with my Bone Density?",
        "Will CBD help with my Sex Drive?",
        "Will CBD help with my Ovarian Cancer Treatment Side Effects?",
        "Will CBD help with my Throat Cancer Treatment Side Effects?",
        "Will CBD help with my Beast Cancer Treatment Side Effects?",
        "Will CBD help with my Colon Cancer Treatment Side Effects?",
        "Will CBD help with my Damaged Nerves?",
        "Will CBD help with my Enlarged Prostate?",
        "Will CBD help with my Prostate Cancer?",
        "Will CBD help with my Muscle Growth?",
        "Will CBD help with my Brain Development?",
        "Will CBD help with my Brain Fog?",
        "Will CBD help with my Focus?",
        "Will CBD help with my Brain Tumor?",
        "Will CBD help with my Lung Cancer Treatment Side Effects?",
        "Will CBD help with my Bladder Cancer Treatment Side Effects?",
        "Will CBD help with my Finger Nail Growth?",
        "Will CBD help with my Creativity?",
        "Will CBD help with my Will CBD help with my Will CBD help with my Chronic Pain?",
        "Is CBD Safe to take with Blood Pressure Medication?",
        "Will CBD Help Me Live Longer?"
    ]
    static let socialMediaPost = [
        "Write a promotional social media post based on the content above",
        "Make promotional social media post for a [product/service]",
        "Write a social media announcement about [product/change/launch]",
        "Write a social media post that generates leads for [product/service]",
        "Write a social media post that drives traffic to [website]",
        "Write a social media post promoting [discount/voucher/promotion]",
        "Create a promotional social media post for an article about [topic]",
        "Write a social media post promoting a [type of event + date]",
        "Write a social media post about [product/service] and include [client pain points]",
        "Describe the impact of using [product/feature] as a [profession/business]",
        "Write X engaging hooks ideas for a social media post about [topic]",
        "Craft a social media post for [product/service] that addresses positive customer emotions",
        "Finish this paragraph: We are launching [product name] to help you [benefit]",
        "Generate a post announcing the launch of our new product [product name]",
        "Create a post highlighting the unique features of our product [product name]",
        "Make a post showcasing the benefits of using our product [product name] for [specific problem/issue]",
        "Develop a post promoting a limited-time sale or discount for our product [product name]",
        "Create a post to encourage customers to leave a review for our product [product name]",
        "Generate a post to create a sense of urgency for buying our product [product name]",
        "Create a social media post that compares our product [product name] with a similar product on the market",
        "Develop a social media post that features customer testimonials for our product [product name]",
        "Make a social media post that demonstrates how our product [product name] can be used in real-life situations",
        "Create a social media post that targets [specific audience] and explains how our product [product name] can help them",
        "Make a social media post listing the benefits of [product/service] for [customer type]",
        "Write a PAS for the content above. (Problem, Agitate, Solve",
        "Write an AIDA for the content above. (Attention, Interest, Desire, Action",
        "Write a BAB about the content above. (Before, After, Bridge",
        "AI-generated social media post example"
    ]
}
// swiftlint:enable line_length type_body_length file_length
